name: BiLang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile and Run Tests
      run: |
        # Define the path to the pre-installed Kotlin standard library
        KOTLIN_STDLIB_PATH="/usr/share/kotlin/lib/kotlin-stdlib.jar"

        # Create the build directory
        mkdir -p build

        # Step 1: Compile all Java sources, including the Kotlin standard library in the classpath
        echo "Compiling Java sources..."
        javac -cp "lib/antlr-4.13.2-complete.jar:$KOTLIN_STDLIB_PATH" -d build \
          src/bilang/*.java \
          generated/bilangGen/*.java

        # Step 2: Compile Kotlin sources, adding the build directory to its classpath
        echo "Compiling Kotlin sources..."
        kotlinc src/bilang/*.kt -cp "build:lib/antlr-4.13.2-complete.jar" -d build

        # Run the compiler with the final, correct classpath
        echo "Running BiLang compiler..."
        kotlin -cp "build:lib/antlr-4.13.2-complete.jar:$KOTLIN_STDLIB_PATH" bilang.MainKt

        # Create a directory for the new output
        mkdir -p new_output/gambit new_output/solidity
        cp examples/gambit/*.efg new_output/gambit/
        cp examples/solidity/*.sol new_output/solidity/

        # Compare generated files with golden masters
        echo "Comparing generated files with golden masters..."
        diff -r examples/gambit new_output/gambit
        diff -r examples/solidity new_output/solidity
