name: BiLang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache ANTLR
      id: cache-antlr
      uses: actions/cache@v4
      with:
        path: antlr-4.13.2-complete.jar
        key: ${{ runner.os }}-antlr-4.13.2

    - name: Download ANTLR if not cached
      if: steps.cache-antlr.outputs.cache-hit != 'true'
      run: wget https://www.antlr.org/download/antlr-4.13.2-complete.jar

    - name: Generate ANTLR Parser
      run: |
        java -jar antlr-4.13.2-complete.jar -o ./generated/bilangGen \
          -package bilangGen -listener -visitor -lib . ./BiLang.g4

    - name: Compile and Run Tests
      run: |
        # Correctly compile the mixed-language project by including both 'src' 
        # (for Kotlin and the Java AstTranslator) and 'generated' (for ANTLR files) 
        # as source directories.
        kotlinc src generated -cp antlr-4.13.2-complete.jar -d build

        # Run the compiler to generate output files
        kotlin -cp build:antlr-4.13.2-complete.jar bilang.MainKt

        # Create a directory for the new output to avoid diffing against itself
        mkdir -p new_output/gambit new_output/solidity
        cp examples/gambit/*.efg new_output/gambit/
        cp examples/solidity/*.sol new_output/solidity/

        # Compare generated files with golden masters
        echo "Comparing generated files with golden masters..."
        diff -r examples/gambit new_output/gambit
        diff -r examples/solidity new_output/solidity
