name: BiLang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven' # Caches Maven dependencies if you add them later

    - name: Cache ANTLR
      id: cache-antlr
      uses: actions/cache@v4
      with:
        path: lib/antlr-4.13.2-complete.jar
        key: ${{ runner.os }}-antlr-4.13.2

    - name: Generate ANTLR Parser
      run: |
        java -jar lib/antlr-4.13.2-complete.jar -o ./generated/bilangGen \
          -package bilangGen -listener -visitor -lib . ./BiLang.g4

    - name: Set up Kotlin
      uses: setup-kotlin/setup-kotlin@v2
      with:
        kotlin-version: '1.9.22'

    - name: Compile BiLang
      run: |
        kotlinc src/bilang/*.kt generated/bilangGen/*.java \
          -cp lib/antlr-4.13.2-complete.jar -d build

    - name: Run Golden Master Test
      run: |
        # Run the compiler to generate output
        kotlin -cp build:antlr-4.13.2-complete.jar bilang.MainKt

        # Create a directory for the new output
        mkdir -p new_output/gambit new_output/solidity

        # Copy generated files to the new output directory
        cp examples/gambit/*.efg new_output/gambit/
        cp examples/solidity/*.sol new_output/solidity/

        # Compare the new output with the committed "golden" versions
        # The diff command will exit with a non-zero status if there are differences
        echo "Comparing generated files with golden masters..."
        diff -r examples/gambit new_output/gambit
        diff -r examples/solidity new_output/solidity
