name: BiLang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Generate ANTLR Parser
      run: |
        # Use the ANTLR jar from the lib directory
        java -jar lib/antlr-4.13.2-complete.jar -o ./generated/bilangGen \
          -package bilangGen -listener -visitor -lib . ./BiLang.g4

    - name: Compile and Run Tests
      run: |
        # Create the build directory
        mkdir -p build

        # Step 1: Compile all Java sources
        echo "Compiling Java sources..."
        javac -cp lib/antlr-4.13.2-complete.jar -d build \
          src/bilang/*.java \
          generated/bilangGen/*.java

        # Step 2: Compile Kotlin sources
        echo "Compiling Kotlin sources..."
        kotlinc src/bilang/*.kt -cp build:lib/antlr-4.13.2-complete.jar -d build

        # Run the compiler to generate output files
        echo "Running BiLang compiler..."
        kotlin -cp build:lib/antlr-4.13.2-complete.jar bilang.MainKt

        # Create a directory for the new output
        mkdir -p new_output/gambit new_output/solidity
        cp examples/gambit/*.efg new_output/gambit/
        cp examples/solidity/*.sol new_output/solidity/

        # Compare generated files with golden masters
        echo "Comparing generated files with golden masters..."
        diff -r examples/gambit new_output/gambit
        diff -r examples/solidity new_output/solidity
