name: BiLang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Compile and Run Tests
      run: |
        # Install SDKMAN and Kotlin to ensure a consistent environment
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install kotlin

        # Create the build directory
        mkdir -p build

        # Step 1: Compile all Java sources. The classpath needs both the ANTLR library
        # (for ANTLR imports) and the Kotlin standard library (for kotlin.Pair).
        echo "Compiling Java sources..."
        javac -cp "lib/antlr-4.13.2-complete.jar:$KOTLIN_HOME/lib/kotlin-stdlib.jar" -d build \
          src/bilang/*.java \
          generated/bilangGen/*.java

        # Step 2: Compile Kotlin sources. The classpath needs the compiled Java classes (`build`)
        # and the ANTLR library (for ANTLR types used in Kotlin code).
        echo "Compiling Kotlin sources..."
        kotlinc src/bilang/*.kt -cp "build:lib/antlr-4.13.2-complete.jar" -d build

        # Step 3: Run the compiled program with the full runtime classpath.
        echo "Running BiLang compiler..."
        kotlin -cp "build:lib/antlr-4.13.2-complete.jar:$KOTLIN_HOME/lib/kotlin-stdlib.jar" bilang.MainKt

        # Step 4: Perform Golden Master Testing for verification.
        echo "Comparing generated files with golden masters..."
        mkdir -p new_output/gambit new_output/solidity
        cp examples/gambit/*.efg new_output/gambit/
        cp examples/solidity/*.sol new_output/solidity/
        diff -r examples/gambit new_output/gambit
        diff -r examples/solidity new_output/solidity
